"""Initial migration

Revision ID: 09eafbbe5670
Revises: 
Create Date: 2026-01-23 14:23:28.317373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09eafbbe5670'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_item')
    # ### end Alembic commands ###
